[features]
seeds = false
skip-lint = false
[programs.devnet]
nitro = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./owner.json"

[workspace]
types = "packages/nitro/src/idl/"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 packages/tests/src/**/*.ts"
